name: nickto
description: Blog
meta_description: "Blog about R, statistics, machine learning"

markdown: kramdown
highlighter: Rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://nickto.github.io'
google_analytics: 'UA-91299295-1'
host: 0.0.0.0
port: 4000

# Details for the RSS feed generator
url:            'https://nickto.github.io'
author:         'nickto'
