baseURL: http://blog.nickto.net/
languageCode: en-gb
title: Notes about various things
theme: ananke

DefaultContentLanguage: en
Paginate: 10
googleAnalytics: 
enableRobotsTXT: true

permalinks:
  posts: /:year-:month-:day-:title/
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
params:
  github: https://github.com/nickto
  gitlab:  https://gitlab.com/nickto
  description: >-
    Notes about data science and related things mostly for myself.  
  featured_image: /home/riga-header.jpg
  disqusShortname: nickto
