baseURL: https://blog.nickto.net/
languageCode: en-gb
title: Notes about random things
theme: PaperMod

DefaultContentLanguage: en
paginattion:
  pagerSize: 10
enableRobotsTXT: true

permalinks:
  posts: /:year-:month-:day-:title/
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: catppuccin-frappe
    tabWidth: 4
  # This enables using raw HTML in markdown
  goldmark:
    renderer:
      unsafe: true
params:
  homeInfoParams:
    Title: Hi there, here you can find some notes
    Content: about data science and (un)related things. Mostly for myself.
  socialIcons: # optional
    - name: "gitlab"
      url: https://gitlab.com/nickto
    - name: "github"
      url: https://github.com/nickto
  ShowShareButtons: true
  comments: true
  disqusShortname: nickto0x64

# services:
#   disqus:
#     shortname: nickto0x64
